In [40]:
#Importing the essential libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
#Loading dataset
dataset=pd.read_csv('Data.csv')
print("-------------------Dataset------------------")
print(dataset)

-------------------Dataset------------------
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [42]:
# Splitting the dataset into indepedent and depedent variable
# x array of matrix is variable for an input dataset
x=dataset.iloc[:,:-1].values
# y array of vector is variable for an output dataset
y=dataset.iloc[:,-1].values
print("-----------indepedent input variable-----------------")
print(x)
print("-----------depedent output variable-----------------")
print(y)

-----------indepedent input variable-----------------
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
-----------depedent output variable-----------------
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [43]:
# Handling the missing value from our dataset
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print("----------------After Handling missing values ---------------------")
print(x)

----------------After Handling missing values ---------------------
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


C:\ProgramData\Anaconda2\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [44]:
# Encoding the categorical values in numerical values for country and output column
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
labelencoder_x.fit(x[:,0])
x[:,0]=labelencoder_x.transform(x[:,0])
print("---------------Encoding for input data----------------")
print(x)
print("---------------Encoding for output data----------------")
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y)

---------------Encoding for input data----------------
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
---------------Encoding for output data----------------
[0 1 0 0 1 1 0 1 0 1]


In [45]:
# Encoding numerical values into dummy variable
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(categorical_features=[0])
x=encoder.fit_transform(x).toarray()
print("----------------After encoding numeric to dummy values-------------------")
print(x)

----------------After encoding numeric to dummy values-------------------
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


C:\ProgramData\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [46]:
# Handling the dummy variable trap
x=x[:,1:]
print('------------------After handling the dummy variable trap---------------')
print(x)

------------------After handling the dummy variable trap---------------
[[0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 0.00000000e+00 3.70000000e+01 6.70000000e+04]]


In [47]:
# Applying feature scaling to keep all values in same scale
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
x=std.fit_transform(x)
print("----------------After applying standardize scale technique---------------")
print(x)
# No need to apply standardizing technique to output value because values are in the rage from 0 to 1

----------------After applying standardize scale technique---------------
[[-6.54653671e-01 -6.54653671e-01  7.58874362e-01  7.49473254e-01]
 [-6.54653671e-01  1.52752523e+00 -1.71150388e+00 -1.43817841e+00]
 [ 1.52752523e+00 -6.54653671e-01 -1.27555478e+00 -8.91265492e-01]
 [-6.54653671e-01  1.52752523e+00 -1.13023841e-01 -2.53200424e-01]
 [ 1.52752523e+00 -6.54653671e-01  1.77608893e-01  6.63219199e-16]
 [-6.54653671e-01 -6.54653671e-01 -5.48972942e-01 -5.26656882e-01]
 [-6.54653671e-01  1.52752523e+00  0.00000000e+00 -1.07356980e+00]
 [-6.54653671e-01 -6.54653671e-01  1.34013983e+00  1.38753832e+00]
 [ 1.52752523e+00 -6.54653671e-01  1.63077256e+00  1.75214693e+00]
 [-6.54653671e-01 -6.54653671e-01 -2.58340208e-01  2.93712492e-01]]
